from __future__ import annotations

from typing import Callable, Dict, List, Sequence, Tuple

import numpy as np
import pandas as pd


# feature_name -> (extractor, period, offset)
_FEATURE_SPECS: Dict[str, Tuple[Callable[[pd.DatetimeIndex], np.ndarray], int, int]] = {
    "hour": (lambda idx: idx.hour.to_numpy(dtype=np.int32), 24, 0),
    "day_of_week": (lambda idx: idx.dayofweek.to_numpy(dtype=np.int32), 7, 0),
    "day_of_month": (lambda idx: idx.day.to_numpy(dtype=np.int32), 31, 1),
    "month": (lambda idx: idx.month.to_numpy(dtype=np.int32), 12, 1),
    "day_of_year": (lambda idx: idx.dayofyear.to_numpy(dtype=np.int32), 366, 1),
    "week_of_year": (lambda idx: idx.isocalendar().week.to_numpy(dtype=np.int32), 53, 1),
}


def get_time_feature_columns(
    features: Sequence[str] | None = None,
    encoding: str = "cyclical",
) -> List[str]:
    """Return the column names generated by add_time_features()."""
    if features is None:
        features = ["hour"]
    encoding = str(encoding).lower()

    cols: List[str] = []
    for feat in features:
        if feat not in _FEATURE_SPECS:
            raise ValueError(
                f"Unknown time feature '{feat}'. "
                f"Supported: {sorted(_FEATURE_SPECS.keys())}"
            )
        _, period, offset = _FEATURE_SPECS[feat]
        if encoding == "raw":
            cols.append(f"tf_{feat}")
        elif encoding == "cyclical":
            cols.extend([f"tf_sin_{feat}", f"tf_cos_{feat}"])
        elif encoding == "both":
            cols.extend([f"tf_{feat}", f"tf_sin_{feat}", f"tf_cos_{feat}"])
        elif encoding == "onehot":
            vals = range(offset, offset + period)
            cols.extend([f"tf_{feat}_{v}" for v in vals])
        else:
            raise ValueError(
                f"Unknown time-feature encoding '{encoding}'. "
                "Use one of: raw, cyclical, both, onehot"
            )
    return cols


def add_time_features(
    df: pd.DataFrame,
    features: Sequence[str] | None = None,
    encoding: str = "cyclical",
) -> pd.DataFrame:
    """Add configurable time features from DatetimeIndex.

    Parameters
    ----------
    features : sequence of str, default ["hour"]
        Supported: hour, day_of_week, day_of_month, month, day_of_year, week_of_year.
    encoding : {"raw", "cyclical", "both", "onehot"}, default "cyclical"
    """
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("DataFrame must be indexed by DatetimeIndex for time features.")

    if features is None:
        features = ["hour"]
    encoding = str(encoding).lower()

    out = df.copy()
    for feat in features:
        if feat not in _FEATURE_SPECS:
            raise ValueError(
                f"Unknown time feature '{feat}'. "
                f"Supported: {sorted(_FEATURE_SPECS.keys())}"
            )
        extractor, period, offset = _FEATURE_SPECS[feat]
        vals = extractor(out.index).astype(np.float32)

        if encoding in {"raw", "both"}:
            out[f"tf_{feat}"] = vals

        if encoding in {"cyclical", "both"}:
            phase = 2.0 * np.pi * ((vals - float(offset)) / float(period))
            out[f"tf_sin_{feat}"] = np.sin(phase).astype(np.float32)
            out[f"tf_cos_{feat}"] = np.cos(phase).astype(np.float32)

        if encoding == "onehot":
            vals_i = vals.astype(np.int32)
            for v in range(offset, offset + period):
                out[f"tf_{feat}_{v}"] = (vals_i == v).astype(np.float32)

    return out
